### ISSUE TITLE
Working on a partial mesh

### ISSUE THREAD

**Issue by hochshi** [Treecodes/TABI-PB#19]
Hi,

Would it be possible to solve the linearized Poisson-Boltzmann equation on a partial mesh that does not cover the entirety of the protein? I would like to solve PB in a binding site with a very high density and am not interested in the electrostatic potential outside that site.

I can change this either in NanoShaper or TABI-PB but before doing so would like to make sure the calculation would still be correct.

Thanks

**Comment by leightonw-cerebras** [comment]
Hi there @hochshi! This is a good question... my intuition says you might have substantial accuracy problems, since the integral equation transforms the domain onto the surface of the mesh. Solving on just a partial mesh may work better with something like a finite difference solver than a boundary element solver.

By the way, I only just notice your issue from awhile back:

> I've modernized parts of NanoShaper, plus added a usable python interface. I think it make sense for you to use NanoShaper as a library instead of executing it.
> If you're interested, have a look at: https://github.com/hochshi/NanoShaper.
> If there's something I can assist with or extra features you'd like to have - drop a line.

Can't believe I missed this! Yes, integrating NanoShaper as a library would make a lot more sense, and back in my PhD I always meant to try, but never got around to it. Would definitely be interested in doing this if I can grab some free time

**Comment by hochshi** [comment]
@leightonw-cerebras thank you. 
I've reread TABI-PB papers and I think I understand your point. 

Since I'm interested in the potential on the surface of the protein using finite difference or finite element solvers isn't really useful for me. 

What do you think about this approach?

I'll produce a mesh of varying densities. The mesh would consist of low density outside the binding site and high density in the binding site.

From my understanding of the integral equations, there is no uniform density requirement, of course calculating energies (such as solvation or binding) this way would lead to higher errors but I'm not interested in energies, only in the electrostatic potential.

Thanks

**Comment by lwwilson1** [comment]
Yes, that should absolutely work—as long as the mesh is closed, it should be fine to have a mesh with higher density close to the binding site. There’s definitely no requirement that the density of the mesh be uniform.

Leighton

**Comment by hochshi** [comment]
Thank you very much. 
If you're interested I'll send the paper once it's published.
